apiVersion: v1
kind: Pod
metadata:
  name: kafka-single-pod
  labels:
    app: kafka
spec:
  containers:
    - name: zookeeper
      image: confluentinc/cp-zookeeper:7.5.0
      env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2181"
        - name: ZOOKEEPER_TICK_TIME
          value: "2000"
      ports:
        - containerPort: 2181
    - name: kafka
      image: confluentinc/cp-kafka:7.5.0
      env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "localhost:2181"
        - name: KAFKA_LISTENERS
          value: "PLAINTEXT://0.0.0.0:9092"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://kafka-single-pod:9092"
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
      ports:
        - containerPort: 9092
  restartPolicy: Always
